### ISSUE TITLE
RuntimeException: Unable to start receiver com.ironz.binaryprefs.dump.DumpReceiver

### ISSUE THREAD

**Issue by dkrivoruchko** [yandextaxitech/binaryprefs#53]
Library version: 1.0.1
Android version: 5.0.2 (Looks like only on this version)
Devices: Defy Mini,  Batmobile XT320

`Exception: java.lang.RuntimeException: Unable to start receiver com.ironz.binaryprefs.dump.DumpReceiver: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null object reference
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:2586)
       at android.app.ActivityThread.access$1700(ActivityThread.java:144)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1355)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5221)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null object reference
       at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:746)
       at java.util.concurrent.ConcurrentHashMap.containsKey(ConcurrentHashMap.java:774)
       at com.ironz.binaryprefs.dump.DumpReceiver.onReceive(DumpReceiver.java:25)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:2579)
       at android.app.ActivityThread.access$1700(ActivityThread.java:144)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1355)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5221)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
`

**Comment by MaxMyalkin** [comment]
It looks like you forgot to put "pref_name" string extra to broadcast intent

**Comment by iamironz** [comment]
Max, correct. Sorry for the long answer.

**Comment by agap** [comment]
> Android version: 5.0.2 (Looks like only on this version)

I noticed a similar crash on Android 6.0.1, Nexus 4. Since Nexus 4 never had an official update to 6.0, I assume this could be some fake device or something.

Batmobile XT320, which is also mentioned in the OP's message, also seems to be a [fake device](https://stackoverflow.com/questions/46845607/is-batmobile-defy-mini-a-fake-device).
